---
version: '3.5'
services:
  sftp-server:
    image: atmoz/sftp
    hostname: sftp-server
    container_name: sftp-server
    ports:
      - "2222:22"
    command: foo:pass:::upload
    volumes:
      - ../../connect/connect-sftp-sink/ssh_host_rsa_key.pub:/home/foo/.ssh/keys/id_rsa.pub:ro

  connect:
    volumes:
      - ../../connect/connect-sftp-sink/ssh_host_rsa_key.pem:/tmp/ssh_host_rsa_key.pem:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-sftp