---
version: '3.5'
services:

  connect:
    volumes:
      - ../../environment/rbac-sasl-plain/scripts/security/client_sasl_plain.config:/etc/kafka/secrets/client_sasl_plain.config
      - ../../troubleshooting/cc-15645/data:/data
    environment:
      # in newer version, it is located in /usr/share/filestream-connectors
      CONNECT_PLUGIN_PATH: /usr/share/java/,/usr/share/confluent-hub-components/,/usr/share/filestream-connectors
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLED: "false"