---
version: '3.5'
services:

  connect:
    volumes:
      - ../../other/secrets-management/secrets:/etc/kafka/secrets
    environment:
      # in newer version, it is located in /usr/share/filestream-connectors
      CONNECT_PLUGIN_PATH: /usr/share/java/,/usr/share/confluent-hub-components/,/usr/share/filestream-connectors
      CONNECT_CONFIG_PROVIDERS: file,securepass
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
      CONNECT_CONFIG_PROVIDERS_SECUREPASS_CLASS: io.confluent.kafka.security.config.provider.SecurePassConfigProvider
      # /etc/confluent/docker/docker-utils.jar is for 5.X versions
      CUB_CLASSPATH: "/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-security/connect/*:/usr/share/java/kafka/*:/usr/share/java/cp-base/*:/usr/share/java/cp-base-new/*"
      CONNECT_PRODUCER_SSL_KEY_PASSWORD: $${securepass:/etc/kafka/secrets/secret.txt:my-config-file.properties/my-secret-property}
      CONFLUENT_SECURITY_MASTER_KEY: ${CONFLUENT_SECURITY_MASTER_KEY}
