---
version: '3.5'
services:
  connect:
    volumes:
      - $HOME/.aws/$AWS_CREDENTIALS_FILE_NAME:$CONNECT_CONTAINER_HOME_DIR/.aws/credentials
      - $HOME/.aws/config:$CONNECT_CONTAINER_HOME_DIR/.aws/config
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-s3,/usr/share/confluent-hub-components/jcustenborder-kafka-connect-transform-common

  producer-repro-95888:
    build:
      context: ../../reproduction-models/connect-connect-aws-s3-sink/producer-repro-95888/
    hostname: producer-repro-95888
    container_name: producer-repro-95888
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOPIC: "customer_avro"
      REPLICATION_FACTOR: 1
      NUMBER_OF_PARTITIONS: 1
      NB_MESSAGES: 10 # -1 for MAX_VALUE
      MESSAGE_BACKOFF: 1000 # Frequency of message injection
      KAFKA_ACKS: "all" # default: "1"
      KAFKA_REQUEST_TIMEOUT_MS: 20000
      KAFKA_RETRY_BACKOFF_MS: 500
      KAFKA_CLIENT_ID: "my-java-producer-repro-95888"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      EXTRA_ARGS: 
    volumes:
      - ../../environment/plaintext/jmx-exporter:/usr/share/jmx_exporter/
