---
version: '3.5'
services:
  client:
    build:
        context: ../../reproduction-models/ccloud-client-kafkajs/
    hostname: client
    container_name: client
    entrypoint: ["sh", "-c", "sleep 2073600"]
    privileged: true
