---
version: '3.5'
services:

  connect:
    volumes:
      - ../../connect/connect-http-sink/security:/tmp
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-http

  # for testing error 302
  http-service-no-auth-302:
    image: vdesabou/http-service-no-auth-302
    hostname: http-service-no-auth-302
    container_name: http-service-no-auth-302
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'simple-auth'