---
version: '3.5'
services:
  ibmmq:
    image: ibmcom/mq # https://hub.docker.com/r/ibmcom/mq/
    hostname: ibmmq
    container_name: ibmmq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: passw0rd
      MQ_APP_PASSWORD: passw0rd
    ports:
      - '1414:1414'
      - '9443:9443'

  # https://github.com/shkoliar/docker-ngrok
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - ibmmq
    environment:
      DOMAIN: ibmmq
      PORT: 1414
      PROTOCOL: tcp
      REGION: eu
      AUTH_TOKEN: $NGROK_AUTH_TOKEN
      DEBUG: "true"