---
version: '3.5'
services:

  producer-88601:
    build:
      context: ../../reproduction-models/connect-connect-azure-data-lake-storage-gen2-sink/producer-88601
    hostname: producer-88601
    container_name: producer-88601
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOPIC: "customer-avro"
      REPLICATION_FACTOR: 1
      NUMBER_OF_PARTITIONS: 1
      MESSAGE_BACKOFF: 1000 # Frequency of message injection
      KAFKA_ACKS: "all" # default: "1"
      KAFKA_REQUEST_TIMEOUT_MS: 20000
      KAFKA_RETRY_BACKOFF_MS: 500
      KAFKA_CLIENT_ID: "my-java-producer"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  connect:
    volumes:
        - ../../reproduction-models/connect-connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf
        - ../../reproduction-models/connect-connect-azure-data-lake-storage-gen2-sink/kafka-connect-transform-archive:/tmp/kafka-connect-transform-archive
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-azure-data-lake-gen2-storage,/tmp/kafka-connect-transform-archive