---
version: '3.5'
services:

  zookeeper:
    profiles:
    - zookeeper

  broker:
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9092,CONTROLLER://broker:29093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # To avoid confluent.cluster.link.enable cannot be enabled with KRaft brokers at this time
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "false"
      # To avoid confluent.balancer.enable cannot be enabled with KRaft brokers at this time
      KAFKA_CONFLUENT_BALANCER_ENABLE: "false"
    volumes:
      - ../../environment/kraft-plaintext/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
