---
version: '3.5'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.13
    hostname: mosquitto
    container_name: mosquitto
    volumes:
      - ../../ccloud/connect-mqtt-source/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../../ccloud/connect-mqtt-source/password:/etc/mosquitto/passwd

  connect:
    depends_on:
      - mosquitto
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-mqtt