---
version: '3.5'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker1:
    # https://hub.docker.com/r/bitnami/kafka
    image: bitnami/kafka:1.1.1
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_CFG_MESSAGE_MAX_BYTES: 10048588
      ALLOW_PLAINTEXT_LISTENER: 'yes'


  broker2:
    image: bitnami/kafka:1.1.1
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_CFG_MESSAGE_MAX_BYTES: 10048588
      ALLOW_PLAINTEXT_LISTENER: 'yes'


  broker3:
    image: bitnami/kafka:1.1.1
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_CFG_MESSAGE_MAX_BYTES: 10048588
      ALLOW_PLAINTEXT_LISTENER: 'yes'

  # connect is used to launch mirrormaker 2 executable
  connect:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    volumes:
        - ../../reproduction-models/ccloud-mirrormaker2/connect-log4j.properties:/tmp/connect-log4j.properties
    environment:
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/connect-log4j.properties"