---
version: '3.5'
services:

  connect:
    volumes:
        - ../../connect/connect-gcp-bigtable-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-gcp-bigtable
      CONNECT_CONFLUENT_TOPIC: "my_license_topic"
      CONNECT_CONFLUENT_LICENSE: "your license here"
      CONNECT_CONFLUENT_TOPIC_BOOTSTRAP_SERVERS: "$BOOTSTRAP_SERVERS"
      CONNECT_CONFLUENT_TOPIC_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: "3"
      CONNECT_CONFLUENT_TOPIC_SASL_MECHANISM: "PLAIN"
      CONNECT_CONFLUENT_TOPIC_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG