---
version: '3.5'
services:
  connect:
    volumes:
        - ../../connect/connect-gcp-bigtable-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-gcp-bigtable
      CONNECT_CONFLUENT_TOPIC: "my_license_topic"
      CONNECT_CONFLUENT_TOPIC_BOOTSTRAP_SERVERS: "broker:9092"
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: "1"