---
version: '3.5'
services:
  connect:
    volumes:
        - ../../reproduction-models/connect-connect-gcp-bigquery-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/wepay-kafka-connect-bigquery
      KAFKA_HEAP_OPTS: " -Xms256M -Xmx6G"

  producer-repro-milli:
    build:
      context: ../../reproduction-models/connect-connect-gcp-bigquery-sink/producer-repro-milli/
    hostname: producer-repro-milli
    container_name: producer-repro-milli
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOPIC: "customer_avro"
      REPLICATION_FACTOR: 1
      NUMBER_OF_PARTITIONS: 1
      NB_MESSAGES: 1000000 # -1 for MAX_VALUE
      MESSAGE_BACKOFF: 0 # Frequency of message injection
      KAFKA_ACKS: "all" # default: "1"
      KAFKA_REQUEST_TIMEOUT_MS: 20000
      KAFKA_RETRY_BACKOFF_MS: 500
      KAFKA_CLIENT_ID: "my-java-producer-repro-milli"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      EXTRA_ARGS: 
    volumes:
      - ../../environment/plaintext/jmx-exporter:/usr/share/jmx_exporter/
