---
version: '3.5'
services:
  broker-us:
    environment:
      DUMMY_VALUE: "DUMMY_VALUE"

  producer-repro-92626:
    build:
      context: ../../reproduction-models/multi-data-center-replicator-connect/producer-repro-92626/
    hostname: producer-repro-92626
    container_name: producer-repro-92626
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker-europe:9092
      TOPIC: "customer_avro"
      REPLICATION_FACTOR: 1
      NUMBER_OF_PARTITIONS: 1
      NB_MESSAGES: 10 # -1 for MAX_VALUE
      MESSAGE_BACKOFF: 1000 # Frequency of message injection
      KAFKA_ACKS: "all" # default: "1"
      KAFKA_REQUEST_TIMEOUT_MS: 20000
      KAFKA_RETRY_BACKOFF_MS: 500
      KAFKA_CLIENT_ID: "my-java-producer-repro-92626"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      EXTRA_ARGS: 
    volumes:
      - ../../environment/plaintext/jmx-exporter:/usr/share/jmx_exporter/
