---
version: '3.5'
services:

  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    depends_on:
    - schema-registry
    ports:
      - "8888:8888"
    volumes:
      - ../../other/http-proxy-schema-registry/nginx-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf
